# 딥러닝및실습-1차-이성수-2019136093

## 1_1-a 텐서화 및 초기화(initialization)

In [1]:
import torch

t1 = torch.Tensor([1, 2, 3], device='cpu') #텐서화 시켜라, PyTorch의 기본 텐서 타입 클래스(대문자)
print(t1.dtype) #기본 dtype은 항상 float32(인자로 다른 dtype 넣어도 적용 안 됨)
print(t1.device) #기본 device는 cpu
print(t1.requires_grad) #텐서는 고정된 연산이나 입력 결과 취급(default option = false)
print(t1.size()) #텐서의 모양
print(t1.shape) #size() 함수와 같은 결과

# if you have gpu device
# t1_cuda = t1.to(torch.device('cuda')) 이런 것도 가능하다!
# or you can use shorthand
# t1_cuda = t1.cuda()
#가급적 GPU로 올려서 연산하는 것이 좋다!
t1_cpu = t1.cpu()

print("#" * 50, 1)

#torch.tensor의 함수
t2 = torch.tensor([1, 2, 3], device='cpu') #텐서 생성에 관한 Factory Function, 대문자 함수보다 이거를 주로 사용, 입력 데이터 타입 자동 추론, 데이터 타입 지정 가능
print(t2.dtype) #1, 2, 3으로부터 int64를 추론
print(t2.device)
print(t2.requires_grad)
print(t2.size()) #3개의 방 => ndim = 1
print(t2.shape)

t2_cpu = t2.cpu()

print("#" * 50, 2)
# 꺽새('[')의 개수에 따라 차원(ndim=rank)이 결정됨
a1 = torch.tensor(1) #허용하지만 방이 하나도 없음, 스칼라
print(a1.shape, a1.ndim) #undimention에 1개의 원소가 존재한다.

a2 = torch.tensor([1]) #방이 하나가 있음, 꺽새('[')가 하나 있으니 1차원(rank)
print(a2.shape, a2.ndim) #(1, )

a3 = torch.tensor([1, 2, 3, 4, 5]) #방 하나에 5개의 원소가 있다, 1차원
print(a3.shape, a3.ndim) #(5, )

a4 = torch.tensor([[1], [2], [3], [4], [5]]) #5개의 방에 원소가 하나씩 있다.
print(a4.shape, a4.ndim) #(5, 1), 2차원

a5 = torch.tensor([ #3개의 방에 원소가 2개씩 있다. 2차원
    [1, 2],
    [3, 4],
    [5, 6]
])
print(a5.shape, a5.ndim)
a6 = torch.tensor([ #torch.size([3, 2, 1]), ndim = 3
    [[1], [2]],
    [[3], [4]],
    [[5], [6]]
])
print(a6.shape, a6.ndim)

a7 = torch.tensor([ #4차원, 3개의 방 안에 1개의 방 안에 2개의 방 안에 1개의 원소
    [[[1], [2]]],
    [[[3], [4]]],
    [[[5], [6]]]
])
print(a7.shape, a7.ndim) #(3, 1, 2, 1)

a8 = torch.tensor([ #4차원, 3개의 방 안에 1개의 방 안에 2개의 방 안에 3개의 원소
    [[[1, 2, 3], [2, 3, 4]]],
    [[[3, 1, 1], [4, 4, 5]]],
    [[[5, 6, 2], [6, 3, 1]]]
])
print(a8.shape, a8.ndim) #(3, 1, 2, 3)

a9 = torch.tensor([ #5차원, 3개의 방 안에 1개의 방 안에 2개의 방 안에 3개의 방 안에 1개의 원소
    [[[[1], [2], [3]], [[2], [3], [4]]]],
    [[[[3], [1], [1]], [[4], [4], [5]]]],
    [[[[5], [6], [2]], [[6], [3], [1]]]]
])
print(a9.shape, a9.ndim) #(3, 1, 2, 3, 1)

a10 = torch.tensor([ #2차원, 4개의 방 안에 5개의 원소
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5]
])
print(a10.shape, a10.ndim) #(4, 5)

a10 = torch.tensor([ #a10이 2개?, 3차원, 4개의 방 안에 1개의 방 안에 5개의 원소
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]]
])
print(a10.shape, a10.ndim) #(4, 1, 5)

a11 = torch.tensor([ #4차원, 4개의 방 안에 1개의 방 안에 2개의 방 안에 3개의 원소가 있어야 한다. (4, 1, 2, 3)
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
]) #하지만 [4, 5]는 원소가 2개가 있는 방이기 때문에 오류가 발생한다. 텐서는 array이기 때문이다.

torch.float32
cpu
False
torch.Size([3])
torch.Size([3])
################################################## 1
torch.int64
cpu
False
torch.Size([3])
torch.Size([3])
################################################## 2
torch.Size([]) 0
torch.Size([1]) 1
torch.Size([5]) 1
torch.Size([5, 1]) 2
torch.Size([3, 2]) 2
torch.Size([3, 2, 1]) 3
torch.Size([3, 1, 2, 1]) 4
torch.Size([3, 1, 2, 3]) 4
torch.Size([3, 1, 2, 3, 1]) 5
torch.Size([4, 5]) 2
torch.Size([4, 1, 5]) 3


ValueError: expected sequence of length 3 at dim 3 (got 2)

## 1_1-b 텐서 초기화 : 복사본

In [5]:
import torch
import numpy as np

#l1, l2, l3는 파이썬 코드 / t1, t2, t3는 이미 있는 l을 이용해서 tensor를 만드는 것
#<tensor화 시키는 3가지 방법>
l1 = [1, 2, 3]
t1 = torch.Tensor(l1) #PyTorch의 기본 텐서 타입 클래스(기본 dtype=float32)

l2 = [1, 2, 3]
t2 = torch.tensor(l2) #텐서화 시켜라, 일종의 텐서 생성에 관한 Factory Function

l3 = [1, 2, 3]
t3 = torch.as_tensor(l3) #이 리스트를 tensor로 바꿔

l1[0] = 100
l2[0] = 100
l3[0] = 100
# 결과: 분리되어 있어서 텐서의 첫번째 원소에 넣었지만 반영되지 않는다.
print(t1)
print(t2)
print(t3)

print('#' * 100)

l4 = np.array([1, 2, 3])
t4 = torch.Tensor(l4)

l5 = np.array([1, 2, 3])
t5 = torch.tensor(l5)

l6 = np.array([1, 2, 3]) #NumPy 배열(dtype=int64)
t6 = torch.as_tensor(l6) #여기서 만든 텐서는 뷰(view)이다

l4[0] = 100
l5[0] = 100
l6[0] = 100 # 텐서 객체의 첫번째 원소를 바꿀 수 있다!(메모리를 공유하기 때문)

print(t4)
print(t5)
print(t6)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])
####################################################################################################
tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([100,   2,   3])


### 1_1-b 정리
1. torch.tensor와 torch.Tensor(생성자) : 복사하기 때문에 원본 객체를 수정하면 텐서는 전혀 변하지 않는다.
    - torch.Tensor & torch.tensor always copies the given data
2. torch.as_tensor : "가능하면 그대로 사용한다", 메모리 효율성을 높이고 불필요한 복사를 피한다. => 원본 NumPy 배열을 바꾸면 텐서도 즉시 반영된다.

3. 언제 어느 함수를 써야 할까?
    - 데이터를 복사해서 독립적인 텐서를 만들고 싶을 때: torch.tensor이나 Tensor
    - 이미 존재하는 NumPy 배열을 바로 활용하고 싶고, 메모리 복사를 피하고 싶을 때(ex 대용량 배열) : torch.as_tensor

## 1_1-c 텐서 초기화 함수 : 상수 값

In [6]:
import torch
#1로 초기화
t1 = torch.ones(size=(5,)) #또는 torch.ones(5), 다양한 방법으로 가능
t1_like = torch.ones_like(input=t1) #이미 만들어져있는 텐서를 넣는다
print(t1)
print(t1_like)
#0으로 초기화
t2 = torch.zeros(size=(6,)) #또는 torch.zeros(*size)
#방이 6개인 1차원 텐서 생성(0으로 채워짐)
#*size는 파이썬의 가변 인자(unpacking) 문법, 텐서의 차원 크기(shape)을 가변적 지정 가능
t2_like = torch.zeros_like(input=t2) #모습이 동일한 텐서가 똑같이 만들어짐
print(t2)
print(t2_like)

t3 = torch.empty(size=(4,)) #안에 원소에 쓰레기값, 아무런 값이 없다.
t3_like = torch.empty_like(input=t3)
print(t3)
print(t3_like)

t4 = torch.eye(n=3) #3x3짜리 항등행렬, identity matrix
print(t4)



tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.])
tensor([0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0.])
tensor([0., 0., 0., 0.])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


## 1_1-d 텐서 초기화 : 랜덤한 값


In [7]:
import torch
#전부 텐서이다.
t1 = torch.randint(low=10, high=20, size=(1, 2)) #10부터 20전까지 랜덤
print(t1)

t2 = torch.rand(size=(1, 3)) #[0, 1)(0은 inclusive 1은 exclusive)float값
print(t2)

t3 = torch.randn(size=(1, 3)) #normal, 정규분포(가우시안 분포), 0에 가까운 값이 많이 나온다.
print(t3)

t4 = torch.normal(mean=10.0, std=1.0, size=(3, 2)) #평균, 표준편차
print(t4)

t5 = torch.linspace(start=0.0, end=5.0, steps=3) #lin: 일자형, space : 간격, 일자형의 간격을 두면서 값을 만들어냄(steps만큼의 값이 같은 간격을 가짐)
print(t5)

t6 = torch.arange(5) #[start, end), step을 안 주면 1씩 증가
print(t6)

print("#" * 30)

torch.manual_seed(1729) #랜덤하게 나오는 값들을 seed를 설정함으로써 “재현”할 수 있다.
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

print()

torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)

tensor([[15, 17]])
tensor([[0.7245, 0.9582, 0.7897]])
tensor([[0.9937, 0.3826, 0.4306]])
tensor([[10.8845,  9.0170],
        [10.4218, 10.4674],
        [10.4468,  8.7545]])
tensor([0.0000, 2.5000, 5.0000])
tensor([0, 1, 2, 3, 4])
##############################
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


## 1_1-e 텐서 타입 규칙


In [8]:
import torch

a = torch.ones((2, 3)) #일텐서
print(a.dtype) #텐서의 타입 확인 가능

b = torch.ones((2, 3), dtype=torch.int16) #타입까지 지정
print(b)

c = torch.rand((2, 3), dtype=torch.float64) * 20. #broadcasting해서 곱해줌
print(c)

d = c.to(torch.int32) #실수 텐서 c의 타입을 정수로 변환
print(d)

#double과 short 텐서를 생성하는 4가지 방법(double : float64, short : int16)
double_d = torch.ones(10, 2, dtype=torch.double)
short_e = torch.tensor([[1, 2]], dtype=torch.short)

double_d = torch.zeros(10, 2).double()
short_e = torch.ones(10, 2).short()

double_d = torch.zeros(10, 2).to(torch.double)
short_e = torch.ones(10, 2).to(dtype=torch.short)

double_d = torch.zeros(10, 2).type(torch.double)
short_e = torch.ones(10, 2).type(dtype=torch.short)

print(double_d.dtype)
print(short_e.dtype)

double_f = torch.rand(5, dtype=torch.double)
short_g = double_f.to(torch.short)
print((double_f*short_g).dtype) #float64 * int16 = float



torch.float32
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[18.0429,  7.2532, 19.6519],
        [10.8626,  2.1505, 19.6913]], dtype=torch.float64)
tensor([[18,  7, 19],
        [10,  2, 19]], dtype=torch.int32)
torch.float64
torch.int16
torch.float64


## 1_1-f 텐서 연산 : add sub mul div


In [9]:
import torch
# shape이 2x2인 텐서들의 연산
print("더하기")
t1 = torch.ones(size=(2, 3))
t2 = torch.ones(size=(2, 3))
t3 = torch.add(t1, t2)
t4 = t1 + t2
print(t3)
print(t4)

print("뺴기")
t5 = torch.sub(t1, t2)
t6 = t1 - t2
print(t5)
print(t6)

print("곱하기")
t7 = torch.mul(t1, t2)
t8 = t1 * t2
print(t7)
print(t8)

print("나누기")
t9 = torch.div(t1, t2)
t10 = t1 / t2
print(t9)
print(t10)


더하기
tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
뺴기
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
곱하기
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
나누기
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


### 1_1-f 텐서 연산 정리
1. element-wise 연산이기 때문에 연산을 해도 shape이 변하지 않는다.
2. 일반적인 연산의 형태와 동치이다.

## 1_1-g 텐서 연산_matrix multiplication



In [10]:
import torch

t1 = torch.dot( #벡터의 내적
    torch.tensor([2, 3]), torch.tensor([2, 1])
)
print(t1, t1.size()) #스칼라 값이 나온다

t2 = torch.randn(2, 3) #정규(가우시안) 분포
t3 = torch.randn(3, 2)
t4 = torch.mm(t2, t3) #행렬 곱셈
print(t4, t4.size())

t5 = torch.randn(10, 3, 4)
t6 = torch.randn(10, 4, 5)
t7 = torch.bmm(t5, t6)
print(t7.size())



tensor(7) torch.Size([])
tensor([[1.6750, 2.2840],
        [0.0956, 1.0294]]) torch.Size([2, 2])
torch.Size([10, 3, 5])


### 1_1-g 텐서 연산_mm 정리
1. 벡터의 내적(x⋅y=a⋅c+b⋅d)은 같은 차원의 두 벡터가 각 성분을 곱해 모두 더하는 연산
    - 결과는 스칼라 값
    - x = (a, b), y = (c, d)
    - 두 벡터의 유사성이나 방향의 일치 정도를 수치로 나타낸다
    - 결과가 0이면 두 벡터는 직교(서로 수직)한다.
2. 행렬 곱셈
    - 두 행렬을 곱해서 새로운 행렬을 만드는 연산
    - 첫번째 행렬의 열 개수와 두 번쨰 행렬의 행 개수가 같아야 한다
        - (m x n) mm (n x p) = m x p

## 1_1-h 텐서 연산_matmul



In [11]:
import torch

t1 = torch.randn(3)                     # 길이 3인 무작위 벡터 생성
t2 = torch.randn(3)                     # 또 다른 길이 3인 무작위 벡터 생성
print(torch.matmul(t1, t2).size())      # 벡터·벡터 내적 → 스칼라, size() 는 torch.Size([])

t3 = torch.randn(3, 4)                  # (3×4) 행렬 생성
t4 = torch.randn(4)                     # 길이 4인 벡터 생성
print(torch.matmul(t3, t4).size())      # 행렬·벡터 곱 → (3,) 벡터, size() 는 torch.Size([3])

t5 = torch.randn(10, 3, 4)              # 배치 10개의 (3×4) 행렬 생성
t6 = torch.randn(4)                     # 길이 4인 벡터 생성
print(torch.matmul(t5, t6).size())      # 각 배치마다 행렬·벡터 곱 → (10, 3) 텐서, size() 는 torch.Size([10, 3])

t7 = torch.randn(10, 3, 4)              # 배치 10개의 (3×4) 행렬 생성
t8 = torch.randn(10, 4, 5)              # 배치 10개의 (4×5) 행렬 생성
print(torch.matmul(t7, t8).size())      # 같은 배치 인덱스끼리 행렬 곱 → (10, 3, 5) 텐서, size() 는 torch.Size([10, 3, 5])

t9 = torch.randn(10, 3, 4)              # 배치 10개의 (3×4) 행렬 생성
t10 = torch.randn(4, 5)                 # (4×5) 행렬 생성 (배치 차원 없음)
print(torch.matmul(t9, t10).size())     # 배치된 행렬과 단일 행렬 곱 → (10, 3, 5) 텐서, size() 는 torch.Size([10, 3, 5])

torch.Size([])
torch.Size([3])
torch.Size([10, 3])
torch.Size([10, 3, 5])
torch.Size([10, 3, 5])


## 1_1-i 텐서 broadcasting



In [15]:
import torch

t1 = torch.tensor([1.0, 2.0, 3.0])
t2 = 2.0
print(t1 * t2)
# 스칼라 값과 벡터 간의 브로드캐스팅 연산 (각 원소에 2가 곱해짐)

print("#" * 50, 1)

t3 = torch.tensor([[0, 1], [2, 4], [10, 10]])
t4 = torch.tensor([4, 5])
print(t3 - t4)
# 2차원 텐서와 1차원 텐서 간 브로드캐스팅 연산 (행마다 적용)

print("#" * 50, 2)

t5 = torch.tensor([[1., 2.], [3., 4.]])
print(t5 + 2.0)  # t5.add(2.0)
print(t5 - 2.0)  # t5.sub(2.0)
print(t5 * 2.0)  # t5.mul(2.0)
print(t5 / 2.0)  # t5.div(2.0)
# 텐서와 스칼라 간 기본 사칙연산 지원

print("#" * 50, 3)

def normalize(x):
    return x / 255

t6 = torch.randn(3, 28, 28)
print(normalize(t6).size())
# normalize 함수로 픽셀값을 [0,1] 범위로 정규화

print("#" * 50, 4)

t7 = torch.tensor([[1, 2], [0, 3]])  # torch.Size([2, 2])
t8 = torch.tensor([[3, 1]])          # torch.Size([1, 2])
t9 = torch.tensor([[5], [2]])        # torch.Size([2, 1])
t10 = torch.tensor([7])              # torch.Size([1])

print(t7 + t8)   # shape (2,2)+(1,2) → 브로드캐스팅
print(t7 + t9)   # shape (2,2)+(2,1) → 브로드캐스팅
print(t8 + t9)   # shape (1,2)+(2,1) → (2,2)로 확장
print(t7 + t10)  # 스칼라와의 브로드캐스팅

print("#" * 50, 5)

t11 = torch.ones(4, 3, 2)
t12 = t11 + torch.rand(3, 2)
# 차원 불일치 시 앞에 축(4)에 대해 브로드캐스팅
print(t12.shape)

t13 = torch.ones(4, 3, 2)
t14 = t13 + torch.rand(3, 1)
# 마지막 차원이 크기 1 → 자동 확장 가능
print(t14.shape)

t15 = torch.ones(4, 3, 2)
t16 = t15 + torch.rand(1, 2)
# 두 번째 차원이 1이라 자동 확장됨
print(t16.shape)

t17 = torch.ones(5, 3, 4, 1)
t18 = torch.rand(3, 1, 1)
# (5,3,4,1)+(3,1,1) → (5,3,4,3) 형성 (브로드캐스팅)
print((t17 + t18).size())

print("#" * 50, 6)

t19 = torch.empty(5, 1, 4, 1)
t20 = torch.empty(3, 1, 1)
print((t19 + t20).size())
# torch.Size([5, 3, 4, 1])

t21 = torch.empty(1)
t22 = torch.empty(3, 1, 7)
print((t21 + t22).size())
# torch.Size([3, 1, 7])

t23 = torch.ones(3, 3, 3)
t24 = torch.ones(3, 1, 3)
print((t23 + t24).size())
# torch.Size([3, 3, 3])

# shape mismatch 예제 (브로드캐스팅 불가능 상황)
# t25 = torch.empty(5, 2, 4, 1)
# t26 = torch.empty(3, 1, 1)
# print((t25 + t26).size())

print("#" * 50, 7)

t27 = torch.ones(4) * 5
print(t27)
# 모든 원소가 5인 벡터

t28 = torch.pow(t27, 2)
print(t28)
# 모든 원소에 대해 제곱

exp = torch.arange(1., 5.)
a = torch.arange(1., 5.)
t29 = torch.pow(a, exp)
print(t29)
# 원소별 거듭제곱 연산


tensor([2., 4., 6.])
################################################## 1
tensor([[-4, -4],
        [-2, -1],
        [ 6,  5]])
################################################## 2
tensor([[3., 4.],
        [5., 6.]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])
################################################## 3
torch.Size([3, 28, 28])
################################################## 4
tensor([[4, 3],
        [3, 4]])
tensor([[6, 7],
        [2, 5]])
tensor([[8, 6],
        [5, 3]])
tensor([[ 8,  9],
        [ 7, 10]])
################################################## 5
torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([5, 3, 4, 1])
################################################## 6
torch.Size([5, 3, 4, 1])
torch.Size([3, 1, 7])
torch.Size([3, 3, 3])
################################################## 7
tensor([5., 5., 5., 5.])
tensor([25., 25., 25., 25.])
tensor([  1

## 1_1-j 텐서 인덱싱과 슬라이싱



In [16]:
import torch

x = torch.tensor(
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9],
   [10, 11, 12, 13, 14]]
)

print(x[1])
# 특정 행(index=1) 선택 → 2차원 텐서에서 1행 전체

print(x[:, 1])
# 모든 행, 1열 선택 → 세로로 뽑아서 1D 텐서 반환

print(x[1, 2])
# (행=1, 열=2) 단일 원소 → 스칼라 텐서

print(x[:, -1])
# 마지막 열 선택 → [4, 9, 14]

print("#" * 50, 1)

print(x[1:])
# 1행부터 끝까지 잘라내기 (슬라이싱)

print(x[1:, 3:])
# 1행부터 끝행까지, 3열 이후만 슬라이싱

print("#" * 50, 2)

y = torch.zeros((6, 6))
y[1:4, 2] = 1
# 1~3행의 2열에 해당하는 원소들만 1로 채움
print(y)

print(y[1:4, 1:4])
# (1~3행, 1~3열)의 하위 블록 추출

print("#" * 50, 3)

z = torch.tensor(
  [[1, 2, 3, 4],
   [2, 3, 4, 5],
   [5, 6, 7, 8]]
)

print(z[:2])
# 0~1행만 추출

print(z[1:, 1:3])
# 1행부터 끝까지, 열 1~2 추출

print(z[:, 1:])
# 전체 행, 열 1부터 끝까지 추출

z[1:, 1:3] = 0
# 부분 슬라이싱 영역을 통째로 0으로 채움 (in-place 수정)
print(z)


tensor([5, 6, 7, 8, 9])
tensor([ 1,  6, 11])
tensor(7)
tensor([ 4,  9, 14])
################################################## 1
tensor([[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])
tensor([[ 8,  9],
        [13, 14]])
################################################## 2
tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
tensor([[0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.]])
################################################## 3
tensor([[1, 2, 3, 4],
        [2, 3, 4, 5]])
tensor([[3, 4],
        [6, 7]])
tensor([[2, 3, 4],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[1, 2, 3, 4],
        [2, 0, 0, 5],
        [5, 0, 0, 8]])


## 1_1-k 텐서 reshaping



In [17]:
import torch

t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = t1.view(3, 2)
# 같은 데이터를 다른 모양(3x2) 으로 재배치
t3 = t1.reshape(1, 6)
# reshape도 모양을 바꾸지만 연속되지 않은 메모리일 경우 view와 달리 복사본을 만들 수 있음
print(t2)
print(t3)

t4 = torch.arange(8).view(2, 4)
# 0~7까지 생성 후 (2,4)로 재배치
t5 = torch.arange(6).view(2, 3)
# 0~5까지 생성 후 (2,3)으로 재배치
print(t4)
print(t5)

print("#" * 50, 1)

t6 = torch.tensor([[[1], [2], [3]]])  # shape = (1,3,1)

t7 = t6.squeeze()
# 크기 1인 차원 모두 제거 → (3,)
t8 = t6.squeeze(0)
# 지정 축(0번 축)이 크기 1 → 제거 가능, 결과 shape=(3,1)
print(t7)
print(t8)

print("#" * 50, 2)

t9 = torch.tensor([1, 2, 3])  # shape = (3,)

t10 = t9.unsqueeze(1)
# 지정 위치(1번 축)에 새 차원 추가 → shape=(3,1)
print(t10)

t11 = torch.tensor([[1, 2, 3], [4, 5, 6]])  # shape = (2,3)
t12 = t11.unsqueeze(1)
# 중간에 차원 삽입 → (2,1,3)
print(t12, t12.shape)

print("#" * 50, 3)

t13 = torch.tensor([[1, 2, 3], [4, 5, 6]])  # shape = (2,3)
t14 = t13.flatten()
# 모든 차원 펼치기 → (6,)
print(t14)

t15 = torch.tensor([[[1, 2],
                     [3, 4]],
                    [[5, 6],
                     [7, 8]]])  # shape = (2,2,2)

t16 = torch.flatten(t15)
# 전체 차원 평탄화 → (8,)
t17 = torch.flatten(t15, start_dim=1)
# dim=1부터 flatten → (2,4)로 변환
print(t16)
print(t17)

print("#" * 50, 4)

t18 = torch.randn(2, 3, 5)
print(t18.shape)
# 원래 (2,3,5)
print(torch.permute(t18, (2, 0, 1)).size())
# (5,2,3)으로 차원 순서 변경

t19 = torch.tensor([[1, 2, 3], [4, 5, 6]])  # shape = (2,3)

t20 = torch.permute(t19, dims=(0, 1))
# 같은 순서라서 shape=(2,3) 그대로
t21 = torch.permute(t19, dims=(1, 0))
# 축 순서 뒤집기 → (3,2)
print(t20)
print(t21)

t22 = torch.transpose(t19, 0, 1)
# 0번 축과 1번 축 교환 → (3,2)
print(t22)

t23 = torch.t(t19)
# 2D 전치(Transpose) → (3,2)
print(t23)


tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[0, 1, 2],
        [3, 4, 5]])
################################################## 1
tensor([1, 2, 3])
tensor([[1],
        [2],
        [3]])
################################################## 2
tensor([[1],
        [2],
        [3]])
tensor([[[1, 2, 3]],

        [[4, 5, 6]]]) torch.Size([2, 1, 3])
################################################## 3
tensor([1, 2, 3, 4, 5, 6])
tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
################################################## 4
torch.Size([2, 3, 5])
torch.Size([5, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


## 1_1-l 텐서 concat



In [18]:
import torch

t1 = torch.zeros([2, 1, 3])
t2 = torch.zeros([2, 3, 3])
t3 = torch.zeros([2, 2, 3])

t4 = torch.cat([t1, t2, t3], dim=1)
print(t4.shape)
# (2, 1, 3), (2, 3, 3), (2, 2, 3)를 dim=1 방향으로 병합 → (2, 6, 3)

print("#" * 50, 1)

t5 = torch.arange(0, 3)  # [0, 1, 2]
t6 = torch.arange(3, 8)  # [3, 4, 5, 6, 7]

t7 = torch.cat((t5, t6), dim=0)
print(t7.shape)
# 1차원 벡터 이어붙이기 → (8,)
print(t7)
# [0, 1, 2, 3, 4, 5, 6, 7]

print("#" * 50, 2)

t8 = torch.arange(0, 6).reshape(2, 3)   # [[0,1,2],[3,4,5]]
t9 = torch.arange(6, 12).reshape(2, 3)  # [[6,7,8],[9,10,11]]

t10 = torch.cat((t8, t9), dim=0)
print(t10.size())
# 행 방향(0번 차원) 확장 → (4,3)
print(t10)

t11 = torch.cat((t8, t9), dim=1)
print(t11.size())
# 열 방향(1번 차원) 확장 → (2,6)
print(t11)

print("#" * 50, 3)

t12 = torch.arange(0, 6).reshape(2, 3)
t13 = torch.arange(6, 12).reshape(2, 3)
t14 = torch.arange(12, 18).reshape(2, 3)

t15 = torch.cat((t12, t13, t14), dim=0)
print(t15.size())
# (2,3) 3개를 행 방향으로 연결 → (6,3)
print(t15)

t16 = torch.cat((t12, t13, t14), dim=1)
print(t16.size())
# (2,3) 3개를 열 방향으로 연결 → (2,9)
print(t16)

print("#" * 50, 4)

t17 = torch.arange(0, 6).reshape(1, 2, 3)
# shape (1,2,3)
t18 = torch.arange(6, 12).reshape(1, 2, 3)
# shape (1,2,3)

t19 = torch.cat((t17, t18), dim=0)
print(t19.size())
# 첫번째 축에서 병합 → (2,2,3)
print(t19)

t20 = torch.cat((t17, t18), dim=1)
print(t20.size())
# 두번째 축에서 연결 → (1,4,3)
print(t20)

t21 = torch.cat((t17, t18), dim=2)
print(t21.size())
# 세번째 축에서 연결 → (1,2,6)
print(t21)


torch.Size([2, 6, 3])
################################################## 1
torch.Size([8])
tensor([0, 1, 2, 3, 4, 5, 6, 7])
################################################## 2
torch.Size([4, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
torch.Size([2, 6])
tensor([[ 0,  1,  2,  6,  7,  8],
        [ 3,  4,  5,  9, 10, 11]])
################################################## 3
torch.Size([6, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])
torch.Size([2, 9])
tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
        [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])
################################################## 4
torch.Size([2, 2, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 4, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 2, 6])
t

## 1_1-m 텐서 stacking



In [19]:
import torch

t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = torch.tensor([[7, 8, 9], [10, 11, 12]])

t3 = torch.stack([t1, t2], dim=0)
t4 = torch.cat([t1.unsqueeze(dim=0), t2.unsqueeze(dim=0)], dim=0)
print(t3.shape, t3.equal(t4))
# t1, t2 shape (2,3)
# stack(dim=0) → (2,2,3), cat은 unsqueeze로 차원을 늘려서 동일 효과

t5 = torch.stack([t1, t2], dim=1)
t6 = torch.cat([t1.unsqueeze(dim=1), t2.unsqueeze(dim=1)], dim=1)
print(t5.shape, t5.equal(t6))
# stack(dim=1) → (2,2,3), cat으로 동일하게 구현 가능

t7 = torch.stack([t1, t2], dim=2)
t8 = torch.cat([t1.unsqueeze(dim=2), t2.unsqueeze(dim=2)], dim=2)
print(t7.shape, t7.equal(t8))
# stack(dim=2) → (2,3,2), cat으로 동일

print("#" * 50, 1)

t9 = torch.arange(0, 3)  # [0,1,2]
t10 = torch.arange(3, 6) # [3,4,5]

print(t9.size(), t10.size())
# (3,), (3,)

t11 = torch.stack((t9, t10), dim=0)
print(t11.size())
# (2,3), 즉 새로운 차원을 위에 쌓음
print(t11)

t12 = torch.cat((t9.unsqueeze(0), t10.unsqueeze(0)), dim=0)
print(t11.equal(t12))
# unsqueeze 후 cat으로 stack과 동일 결과

t13 = torch.stack((t9, t10), dim=1)
print(t13.size())
# (3,2), 즉 원소마다 새로운 차원을 추가
print(t13)

t14 = torch.cat((t9.unsqueeze(1), t10.unsqueeze(1)), dim=1)
print(t13.equal(t14))
# unsqueeze 후 cat으로 stack과 동일 결과


torch.Size([2, 2, 3]) True
torch.Size([2, 2, 3]) True
torch.Size([2, 3, 2]) True
################################################## 1
torch.Size([3]) torch.Size([3])
torch.Size([2, 3])
tensor([[0, 1, 2],
        [3, 4, 5]])
True
torch.Size([3, 2])
tensor([[0, 3],
        [1, 4],
        [2, 5]])
True


## 1_1-n 텐서 stacking



In [1]:
import torch

t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([4, 5, 6])
t3 = torch.vstack((t1, t2))
print(t3)
# vstack: 세로 방향으로 쌓음
# >>> tensor([[1, 2, 3],
#             [4, 5, 6]])

t4 = torch.tensor([[1], [2], [3]])
t5 = torch.tensor([[4], [5], [6]])
t6 = torch.vstack((t4, t5))
print(t6)
# >>> tensor([[1],
#             [2],
#             [3],
#             [4],
#             [5],
#             [6]])

t7 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t7.shape)  # (2, 2, 3)

t8 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t8.shape)  # (2, 2, 3)

t9 = torch.vstack([t7, t8])
print(t9.shape)
# 첫 번째 차원(행) 방향으로 병합 → (4, 2, 3)
print(t9)
# >>> tensor([[[ 1,  2,  3],
#              [ 4,  5,  6]],
#             [[ 7,  8,  9],
#              [10, 11, 12]],
#             [[13, 14, 15],
#              [16, 17, 18]],
#             [[19, 20, 21],
#              [22, 23, 24]]])

print("#" * 50, 1)

t10 = torch.tensor([1, 2, 3])
t11 = torch.tensor([4, 5, 6])
t12 = torch.hstack((t10, t11))
print(t12)
# hstack: 가로 방향으로 붙임
# >>> [1, 2, 3, 4, 5, 6]

t13 = torch.tensor([[1], [2], [3]])
t14 = torch.tensor([[4], [5], [6]])
t15 = torch.hstack((t13, t14))
print(t15)
# >>> [[1, 4],
#      [2, 5],
#      [3, 6]]

t16 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t16.shape)  # (2, 2, 3)

t17 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t17.shape)  # (2, 2, 3)

t18 = torch.hstack([t16, t17])
print(t18.shape)
# 두 번째 차원(열) 방향으로 병합 → (2, 4, 3)
print(t18)
# >>> tensor([[[ 1,  2,  3],
#              [ 4,  5,  6],
#              [13, 14, 15],
#              [16, 17, 18]],
#             [[ 7,  8,  9],
#              [10, 11, 12],
#              [19, 20, 21],
#              [22, 23, 24]]])


tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([4, 2, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]])
################################################## 1
tensor([1, 2, 3, 4, 5, 6])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([2, 4, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [13, 14, 15],
         [16, 17, 18]],

        [[ 7,  8,  9],
         [10, 11, 12],
         [19, 20, 21],
         [22, 23, 24]]])


## 숙제 후기
### 인공지능 과목이 처음이어서 솔직히 많이 힘들었다. 하지만 교수님께서 설명을 너무 잘 해주시고, 조교님께서 질문 답변을 너무 잘 해주셔서 따라갈 수 있었다. 조교님께서 올려주신 텐서 메소드 강의도 너무 유용했다.
### 많이 부족한 실력을 가지고 있어서 강의를 최대한 집중해서 들으며 필기하고 그 내용을 주석으로 적으려고 노력했다. 코드도 직접 쳐 보면서 이해할 수 있었던 좋은 시간이었던 거 같다. 나중에 잘 모르는 부분이 생기면 다시 보러 올 것이다.